common: &common
  fog_credentials:
    :provider: AWS
    :aws_access_key_id: AKIAJXFF6RBMRIJECXYA
    :aws_secret_access_key: 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
    :region: us-west-2

production:
  <<: *common
  fog_directory: investomni.prod
  asset_host: http://investomni.prod.s3.amazonaws.com

development:
  <<: *common
  fog_directory: investomni.dev
  asset_host: http://investomni.dev.s3.amazonaws.com
